const state = { incidents: [], refreshing: false };
const elements = {
  incidentsBody: document.querySelector("#incidents-body"), alertsBody: document.querySelector("#alerts-body"),
  severity: document.querySelector("#severity-filter"), category: document.querySelector("#category-filter"),
  refresh: document.querySelector("#refresh-button"), error: document.querySelector("#error-message"),
  status: document.querySelector("#connection-status"), updated: document.querySelector("#last-updated"),
  drawer: document.querySelector("#incident-drawer"), backdrop: document.querySelector("#drawer-backdrop"), detail: document.querySelector("#incident-detail"), detailTitle: document.querySelector("#detail-title"),
};

function text(value, fallback = "-") { return value === null || value === undefined || value === "" ? fallback : String(value); }
function severityClass(value) { const normalized = text(value, "neutral").toLowerCase(); return ["critical", "high", "medium", "low"].includes(normalized) ? normalized : "neutral"; }
function makeCell(value, className = "") { const cell = document.createElement("td"); cell.textContent = text(value); if (className) cell.className = className; return cell; }
function makeBadge(value) { const badge = document.createElement("span"); badge.className = `badge badge-${severityClass(value)}`; badge.textContent = text(value); return badge; }
function renderEmpty(body, columns, message) { const row = document.createElement("tr"); const cell = document.createElement("td"); cell.colSpan = columns; cell.className = "empty-cell"; cell.textContent = message; row.append(cell); body.replaceChildren(row); }

async function request(path) { const response = await fetch(path, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error(`${path} returned ${response.status}`); return response.json(); }
function setKpis(stats) { [["total", "total_incidents"], ["critical", "critical"], ["high", "high"], ["medium", "medium"], ["low", "low"]].forEach(([id, key]) => { document.querySelector(`#kpi-${id}`).textContent = text(stats[key], "0"); }); }
function populateCategories(incidents) { const selected = elements.category.value; const categories = [...new Set(incidents.map(item => text(item.category, "Unclassified")))].sort(); elements.category.replaceChildren(new Option("All", "")); categories.forEach(category => elements.category.add(new Option(category, category))); elements.category.value = categories.includes(selected) ? selected : ""; }
function filteredIncidents() { return [...state.incidents].filter(item => (!elements.severity.value || item.severity === elements.severity.value) && (!elements.category.value || item.category === elements.category.value)).sort((left, right) => Number(right.risk_score || 0) - Number(left.risk_score || 0)); }
function renderIncidents() { const incidents = filteredIncidents(); if (!incidents.length) return renderEmpty(elements.incidentsBody, 9, "No incidents match the current filters."); const fragment = document.createDocumentFragment(); incidents.forEach(incident => { const row = document.createElement("tr"); row.dataset.incidentId = text(incident.incident_id, ""); row.append(makeCell(incident.incident_id), makeCell("", "severity-cell"), makeCell(incident.risk_score), makeCell(incident.category), makeCell(incident.subcategory), makeCell(incident.agent_name || incident.agent_id), makeCell(incident.first_seen), makeCell(incident.last_seen), makeCell(incident.status)); row.querySelector(".severity-cell").append(makeBadge(incident.severity)); row.addEventListener("click", () => openIncident(incident.incident_id)); fragment.append(row); }); elements.incidentsBody.replaceChildren(fragment); }
function renderAlerts(alerts) { const recent = [...alerts].sort((left, right) => String(right.timestamp || "").localeCompare(String(left.timestamp || ""))).slice(0, 20); if (!recent.length) return renderEmpty(elements.alertsBody, 7, "No recent alerts available."); const fragment = document.createDocumentFragment(); recent.forEach(alert => { const row = document.createElement("tr"); row.append(makeCell(alert.timestamp), makeCell(alert.rule_id), makeCell(alert.rule_description), makeCell(alert.category), makeCell(alert.risk_score), makeCell("", "risk-cell"), makeCell(alert.agent_name || alert.agent_id)); row.querySelector(".risk-cell").append(makeBadge(alert.risk_level)); fragment.append(row); }); elements.alertsBody.replaceChildren(fragment); }
function appendDetailField(container, label, value) { const item = document.createElement("div"); const labelNode = document.createElement("span"); const valueNode = document.createElement("strong"); labelNode.textContent = label; valueNode.textContent = text(value); item.append(labelNode, valueNode); container.append(item); }
function detailSection(title) { const section = document.createElement("section"); const heading = document.createElement("h3"); heading.textContent = title; section.append(heading); return section; }
function openIncident(incidentId) { const incident = state.incidents.find(item => item.incident_id === incidentId); if (!incident) return; elements.detailTitle.textContent = text(incident.title, "Incident detail"); const content = document.createDocumentFragment(); const description = document.createElement("p"); description.textContent = text(incident.description); content.append(description); const summary = document.createElement("div"); summary.className = "detail-summary"; appendDetailField(summary, "Severity", incident.severity); appendDetailField(summary, "Risk score", incident.risk_score); appendDetailField(summary, "Category", incident.category); appendDetailField(summary, "Status", incident.status); content.append(summary);
  const categories = detailSection("Categories"); const categoriesText = document.createElement("p"); categoriesText.textContent = (incident.categories || []).map(value => text(value)).join(", ") || text(incident.category); categories.append(categoriesText); content.append(categories);
  const events = detailSection("Involved event IDs"); const eventList = document.createElement("ul"); (incident.event_ids || []).forEach(value => { const item = document.createElement("li"); item.textContent = text(value); eventList.append(item); }); if (!eventList.children.length) { const item = document.createElement("li"); item.textContent = "No event IDs provided."; eventList.append(item); } events.append(eventList); content.append(events);
  const recommendations = detailSection("Recommendations"); const items = Array.isArray(incident.recommendations) ? incident.recommendations : []; if (!items.length) { const message = document.createElement("p"); message.textContent = "No recommendations available."; recommendations.append(message); } items.forEach(recommendation => { const card = document.createElement("article"); card.className = "recommendation"; const heading = document.createElement("h4"); heading.textContent = text(recommendation.title); const priority = document.createElement("p"); priority.append(makeBadge(recommendation.priority)); const descriptionText = document.createElement("p"); descriptionText.textContent = text(recommendation.description); const rationale = document.createElement("p"); rationale.textContent = `Rationale: ${text(recommendation.rationale)}`; const actions = document.createElement("ul"); (recommendation.actions || []).forEach(action => { const item = document.createElement("li"); item.textContent = text(action); actions.append(item); }); card.append(heading, priority, descriptionText, rationale, actions); recommendations.append(card); }); content.append(recommendations);
  elements.detail.replaceChildren(content); elements.drawer.classList.add("open"); elements.drawer.setAttribute("aria-hidden", "false"); elements.backdrop.hidden = false; }
function closeDrawer() { elements.drawer.classList.remove("open"); elements.drawer.setAttribute("aria-hidden", "true"); elements.backdrop.hidden = true; }
async function refreshDashboard() { if (state.refreshing) return; state.refreshing = true; elements.refresh.disabled = true; elements.status.textContent = "Refreshing"; elements.error.hidden = true; try { const [stats, incidents, alerts] = await Promise.all([request("/statistics"), request("/incidents"), request("/alerts")]); state.incidents = Array.isArray(incidents) ? incidents : []; setKpis(stats || {}); populateCategories(state.incidents); renderIncidents(); renderAlerts(Array.isArray(alerts) ? alerts : []); elements.status.textContent = "Live"; elements.updated.textContent = `Last updated ${new Date().toLocaleTimeString()}`; } catch (error) { elements.status.textContent = "API unavailable"; elements.error.textContent = `Unable to refresh dashboard data. ${text(error.message, "Please try again.")}`; elements.error.hidden = false; } finally { state.refreshing = false; elements.refresh.disabled = false; } }
elements.refresh.addEventListener("click", refreshDashboard); elements.severity.addEventListener("change", renderIncidents); elements.category.addEventListener("change", renderIncidents); document.querySelector("#drawer-close").addEventListener("click", closeDrawer); elements.backdrop.addEventListener("click", closeDrawer); refreshDashboard(); window.setInterval(refreshDashboard, 15000);
